version: '3'

services:
        where_is_systembinsh:
                restart: always
                build: ./
                read_only: true
                networks:
                        - internal
        proxy_1:
                restart: always
                image: nginx
                ports:
                        - '30001:30001'
                volumes:
                        - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
                networks:
                        - default
                        - internal
                depends_on:
                        - where_is_systembinsh

networks:
        default:
        internal:
                internal: true
